### ISSUE TITLE
Research LSP format and dependencies

### ISSUE THREAD

**Issue by nvgrw** [flintrocks/flint#23]
Research the way that the LSP format works and what libraries might be available for Swift to run an LSP server.
https://langserver.org/

**Comment by ethanluoyc** [comment]
Official website:

https://langserver.org/

Official guide for implementing a LSP server/client for VSCode:

https://code.visualstudio.com/docs/extensions/example-language-server

My conclusion:
Note that there is a Swift-version of the LSP protocol [here](https://github.com/owensd/swift-lsp) (MIT licensed). I assumed it to be a programatic implementation of the protocol (and yes it is). They also have a LSP server implemented based on that. We can reuse the LSP protocol and implement our server for Flint on top of that.

**Comment by ethanluoyc** [comment]
swift build -Xswiftc -framework -Xswiftc sourcekitd -Xswiftc -F -Xswiftc /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib -Xlinker -rpath -Xlinker /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib

**Comment by nvgrw** [comment]
Created #42 #43 #44
