### ISSUE TITLE
Crash when using a mutating func in init

### ISSUE THREAD

**Issue by Aurel300** [flintrocks/flint#30]
E.g.

```swift
struct Wei {
  var rawValue: Int

  init(unsafeRawValue: Int) {
    setRawValue(unsafeRawValue)
  }

  mutating func setRawValue(value: Int) -> Int {
    rawValue = value
    return rawValue
  }
}
```

This should output a meaningful error message (assuming IR really cannot be output in this case?) instead of crashing the compiler completely.

**Comment by nvgrw** [comment]
Discussion in https://github.com/flintlang/flint/issues/409

**Comment by nvgrw** [comment]
Needed for #47. Prioritise.

**Comment by Aurel300** [comment]
After discussion changed to #101.
