### ISSUE TITLE
Implement a demo showing compiler error messages when opening the client

### ISSUE THREAD

**Issue by ethanluoyc** [flintrocks/flint#44]

**Comment by ethanluoyc** [comment]
@catalincraciun If you would like to give it a try, start from here https://github.com/flintrocks/flint/blob/lsp/Sources/LSP/langsrvlib/SwiftLanguageServer.swift#L126. Basically, the server will receive some requests from the editor. It then sends the client diagnostics messages. I think if you take a look at the types you should be able to figure out what arguments need to be passed in. In particular, we depend on https://github.com/owensd/swift-lsp/blob/master/Sources/LanguageServerProtocol/Diagnostics.swift. 

I will resume working on this ASAP. Just got a new laptop. I am taking longer to setup because of the network problem in China.

**Comment by ethanluoyc** [comment]
If you would like to try out with the vscode-client. You need to
1. Build flint by running`make`. 
2. Put `.build/debug/langsrv` and `stdlib/` to the directory `lib/usr/bin` in [vscode-flint](https://github.com/flintrocks/vscode-flint).
3. To spawn a test client host. Open VSCode, run tasks from Debug. Then select a flint program and then change the language to Flint (for some reason it no longer auto-detects the language. I am investigating)

**Comment by nvgrw** [comment]
Done, see https://github.com/flintrocks/vscode-flint
