### ISSUE TITLE
Expose an API for compiling Flint programs

### ISSUE THREAD

**Issue by ethanluoyc** [flintrocks/flint#46]
We probably need some API like `compile(path) -> [Diagnostic]`. This can be used by flintc. Moreover, this would be a good way to setup the compiler for the lsp services.

**Comment by nvgrw** [comment]
Is this an API on the server or on the VSCode plugin?

**Comment by ethanluoyc** [comment]
Server.

**Comment by nvgrw** [comment]
Ah cool, just good to clarify since the signature looks kind of JavaScript-y
