### ISSUE TITLE
Research asset traits

### ISSUE THREAD

**Issue by Aurel300** [flintrocks/flint#6]

**Comment by Aurel300** [comment]
I think before we can have this we need either generics with type constraints or polymorphic `This` in flint. Consider:

```
struct trait Asset {
  mutating func transfer(source: inout Asset, amount: Int)
}

struct Wei: Asset {
  mutating func transfer(source: inout Asset, amount: Int) {
    // ...
  }
}

struct Bitcoin: Asset {
  mutating func transfer(source: inout Asset, amount: Int) {
    // ...
  }
}
```

Then you could do:

```
someBitcoinAsset.transfer(someWeiAsset, 1000)
```

Which does not make sense. Solution with polymorphic `This`:

```
struct trait Asset {
  mutating func transfer(source: inout This, amount: Int)
}
```

`source: inout This` restricts `source` to be of the same type as the target.

Solution with generics and type contraints:

```
struct trait Asset<This:Asset<This>> {
  mutating func transfer(source: inout This, amount: Int)
}
```

This is basically the same thing but specified using a generic type parameter.

**Comment by ethanluoyc** [comment]
Parser definitions has been formalized in the grammar

https://github.com/flintrocks/flint/blob/master/docs/grammar.abnf#L10

And implemented in parser
https://github.com/flintrocks/flint/blob/master/Sources/Parser/Parser%2BDeclaration.swift

Note that this is different from the syntax as mentioned in the thesis. Specifically, we now have
struct trait and contract trait.

**Comment by ethanluoyc** [comment]
We basically need to implement traits. My understanding of traits is that they are just interfaces with the ability to add default implementation. Then we need to allow for types to implement a particular trait. The examples @Aurel300 gave is illustrative but incomplete. 

## Implementing multiple traits from the same type
We should allow for implementing multiple traits from the same type. Therefore, you would also be able to do.
```swift
struct trait A {
  mutating func f(source: inout Asset, amount: Int)
}

struct trait B {
  mutating func g(source: inout Asset, amount: Int)
}

struct C: A {
  mutating func f(source: inout Asset, amount: Int) {
    // ...
  }
}

struct C: B {
  mutating func g(source: inout Asset, amount: Int) {
    // ...
  }
}
```
The syntax may need to be updated for trait implementation (see for example [Rust](https://doc.rust-lang.org/book/second-edition/ch10-02-traits.html). We can start with allowing for implementing 1 trait, but can be later extended to handle multiple traits. We should try to clarify we implement the method
dispatch in this context. Maybe it's worthwhile to investigate how modern compilers do these things. (e.g. rust and scala are the two languages that I could think of that have the closest thing to what we are trying to achieve)

## Implementing generics

The concept of generics are also referred to as trait bound in rust's context. See the link above. This would be something that we are looking for. I am not experienced enough to discuss how to design a type system for this kind of things. This would be something that we need to discuss with Susan to see what the options are.

## Open problems
In addition to the points above, one thing that might also be worth investigating would be how the trait implementation would interfere with the languages features that Flint has. e.g. privilliaged operations etc. This would be something that we need to handle which are not usually present other languages.

**Comment by Aurel300** [comment]
> We basically need to implement traits.

? Traits are already implemented and are in the `BehaviorTests` suite. See https://github.com/flintrocks/flint/blob/master/Tests/BehaviorTests/tests/traits/traits.flint.

The feature we need to implement is asset traits specifically, i.e. `struct trait Asset { ... }`. Also, following an e-mail exchange with Susan, the decision is for now to make the `struct trait Asset` have special behaviour in the compiler, in that it will trigger a compiler error when transferring across different currencies.

We may implement generics later, as a separate feature.
