### ISSUE TITLE
Ensure the Swift toolchain works for everyone

### ISSUE THREAD

**Issue by Aurel300** [flintrocks/flint#7]

**Comment by nvgrw** [comment]
Use `swift package generate-xcodeproj` to generate an Xcode project. Regenerate as necessary.

**Comment by ethanluoyc** [comment]
I added this to the Wiki.

**Comment by CalinFarcas** [comment]
I used these instructions to get swiftlint working on Linux.

https://github.com/realm/SwiftLint/issues/732#issuecomment-339815572
