### ISSUE TITLE
Check valid external call returns

### ISSUE THREAD

**Issue by Aurel300** [flintrocks/flint#96]
(From #72)

External traits may optionally specify return types for their function signatures:

```swift
external trait Ext {
  func someFunc()
  func someReturningFunc() -> int256
}
```

External calls are expressions which may have a type if the matching function was declared with a return type. Just like regular function calls, external calls can be used on their own as statements, if the function is void type (no return type).

The return value from external calls with a return type should **never** be ignored, i.e. it should be assigned to a variable, used as an argument, etc. External calls without a return type should only be used as statements.

```swift
// valid usage:
call! ext.someFunc()
do {
  call ext.someFunc()
  let y: Int = call ext.someReturningFunc()
} catch is Error { ... }
if let x: Int = call? ext.someReturningFunc() { ... }

// invalid usage:
call! ext.someReturningFunc()
do {
  call ext.someReturningFunc()
  let y: Int = call ext.someFunc()
} catch is Error { ... }
if let x: Int = call? ext.someFunc() { ... }
```

 - [ ] check that values from `call`s with a return type are not ignored
 - [ ] check that `call`s without a return type are only ever used as statements
 - [ ] check that in `let ... = call ...` the return type matches the variable declared

**Comment by ckamueller** [comment]
Closed with #128, #123
