### ISSUE TITLE
External contract member checks

### ISSUE THREAD

**Issue by Aurel300** [flintrocks/flint#99]
(from #72)

External contracts can be specified with the `external trait` syntax:

```swift
external trait Ext {
  func someFunc()
  func someReturningFunc(param: Int64, other: UInt72) -> Int
}
```

External contracts are severely limited in what can or cannot be specified; a lot of normal trait functionality should be disabled.

 - [x] check that external trait members are only function signatures - no variables, no `init`s, no `fallback`s, no `event`s
 - [x] check that there are no implementations for functions (signature only!)
 - [x] check that there are no protection blocks for external traits
 - [x] check that there are no type states for external traits
 - [ ] check hash collisions (see note at the bottom of https://github.com/flintrocks/flint/issues/73#issuecomment-437690396)
 - [x] check that function signatures only use external (Solidity ABI) types - will be done as a part of #90

**Comment by nvgrw** [comment]
New ticket made #124
